<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-MA03575" failures="2" tests="2" name="Test(failed)" time="0.109" errors="0" timestamp="2023-04-18T00:43:20 IST">
  <testcase classname="RetryTestCases.RetryLogicDemo" name="TestCase02" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryTestCases.RetryLogicDemo.TestCase02(RetryLogicDemo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="RetryTestCases.RetryLogicDemo" name="TestCase01" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryTestCases.RetryLogicDemo.TestCase01(RetryLogicDemo.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="RetryTestCases.RetryLogicDemo" name="TestCase03" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase03 -->
</testsuite> <!-- Test(failed) -->
